### ISSUE TITLE
mc-http-server in production dependencies

### ISSUE THREAD

**Issue by svaj** [commercetools/merchant-center-starter-app#22]
**Describe the bug**
mc-http-server is currently a dev dependency.  The docs mention that is only for production use.  It should probably go into the production dependencies, unless there's a specific reason for it staying in the devDeps.

**Comment by emmenko** [comment]
Good question. No there is not a specific reason. It should probably go to `dependency` yes, but I guess it depends on how you have your deployment setup.

I can move it to `dependency` for this example app. Thanks for the feedback 👌
